// src/domain/jobs/enums/JobType.ts
export enum JobType {
  PF_DRAFT_SCRAPER = 'PF_DRAFT_SCRAPER',
  ESPN_PLAYER_IMPORT = 'ESPN_PLAYER_IMPORT',
  NFL_STATS_IMPORT = 'NFL_STATS_IMPORT',
  IMPORT_SCORES_WEEK = 'IMPORT_SCORES_WEEK', // ← add this
  
  SYNC_TEAMS = 'SYNC_TEAMS',
  BACKFILL_SEASON = 'BACKFILL_SEASON',
  DRAFT_ORDER_COMPUTE = 'DRAFT_ORDER_COMPUTE',
}
